logging:
  config: classpath:log4j2_manage.yml
server:
  port: 9518
  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: manage
  profiles:
    active: local
  datasource:
#    jdbc-url: jdbc:mysql://localhost:3306/managedb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: ONEC
#    password: 2112
#    type: com.zaxxer.hikari.HikariDataSource #com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    useSSL: false
#    maximun-pool-size: 100
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#    validation-query: SELECT 1
#    test-on-borrow: false
#    test-while-idle: true
#    time-between-eviction-runs-millis: 18800
    hikari: # 使用 hikari 数据库连接池
      maximum-pool-size: 100 # 最大链接数
      connection-timeout: 6000 # 1分钟默认30秒
      minimum-idle: 10 # 最小空闲连接数：默认10
      max-lifetime: 540000 #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      connection-test-query: SELECT 1
      jdbc-url: jdbc:mysql://localhost:3306/managedb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: ONEC
      password: 2112
      driver-class-name: com.mysql.cj.jdbc.Driver
      idle-timeout:
      validation-timeout:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.MySQL57Dialect

  redis:
    password: 862112
    #    cluster:
    #      nodes: 127.0.0.1:6379
    #      max-redirects:
    jedis:
      pool:
        max-active: 500
        max-idle: 8
        max-wait: 12
    timeout: 5000
    host: 127.0.0.1
    port: 6379

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java/com
  mail:
    host: smtp.qq.com
    username: 2650020302@qq.com
    password: ijfebctnfnabebac # QQ 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # 配置thymeleaf 模板
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    suffix: .html
  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 10240MB
      max-request-size: 10240MB
  #  配置mq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
# admin 配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
